### ISSUE TITLE
authdecrypt failed: -18

### ISSUE THREAD

**Issue by Claustn** [Asbjoern/Kamstrup-Radius-Interface#2]
Så har jeg langt om længe fået koder fra Radius og ville prøve at se om jeg kunne udlæse noget data.

Jeg har loadet din sketch over på en ESP8266 baseret Lolin NodeMCU v3, og har forbundet den til min Kamstrup måler.
Jeg har konfiguret net og får i loggen denne besked (ca hvert 10 sekund)
`Frame complete
authdecrypt failed: -18
Decryption failed`

Jeg har prøvet at indtaste koder både med "0x" foran og uden, samt prøvet at bytte rundt på dem, men får stadigt samme fejl hver gang, er det noget du er stødt på ?

**Comment by Claustn** [comment]
Sorry, havde ikke set du havde pushet en ny version idag.. Tester lige med den (Ser lovende ud)

PS
Tak for godt arbejde

**Comment by Asbjoern** [comment]
Ja, der var ikke lige plads til streng terminerings karakteren i arrayet. Så rent held det har virket hos mig. God fornøjelse.
